<script>
</script>

<!--Hero section-->
<section class="page-hero">
<div class="hero-container">
<h1>About Rasuwa Hydropower Limited</h1>
<p> Developing sustainable hydropower infrastructure to contribute
      reliable and renewable energy to Nepal’s national grid.</p>
</div>
</section>
<!--Company Introduction-->
<section class="company-introduction">
<div class="container">
<h2>Company Overview</h2>
<p><strong>Rasuwa Hydropower Limited</strong> is a Nepali hydropower development company established on <strong>2066/02/04 B.S.</strong> with the objective of developing sustainable hydropower infrastructure in Nepal. The company is registered in Kathmandu and operates as a limited company engaged in the development, construction and operation of <strong>hydropower projects</strong>. With a focus on responsible energy development, the company aims to harness Nepal’s abundant water resources to contribute reliable and environmentally sustainable electricity to the national grid.</p>
<p> The company is currently developing the <strong>Phalakhu Khola Hydropower Project, a 7.29 MW</strong> run-of-river hydropower project located in <strong>Naukunda Rural Municipality–4, Bhorle, Rasuwa District, Bagmati Province, Nepal.</strong> The project utilizes water from the Phalakhu River system and is designed with a gross head of approximately 181.95 meters and a design discharge of 5.03 cubic meters per second, enabling an estimated annual energy production of <strong>38.74 GWh.</strong> Electricity generated by the project will be transmitted through a 33 kV transmission line to the Trishuli 3B Hub Substation of the Nepal Electricity Authority.</p>
<p><strong>Rasuwa Hydropower Limited</strong> is supported by experienced promoters, technical experts and financial professionals involved in hydropower development, engineering, project management and infrastructure investment. Through the development of hydropower projects, the company aims to strengthen Nepal’s energy security while contributing to sustainable infrastructure development and long-term economic growth</p>
</div>
</section>
<!--Objectives-->
<section class="objectives">
<div class="objective-container-grid">
    <div class="primary-objective">
        <h1>🎯</h1>
        <h3>Primary Objective</h3>
        <p> To develop and implement the Phalakhu Khola Hydropower Project
        (7.29 MW) in Rasuwa District, utilizing Nepal’s natural river
        resources to generate clean and renewable electricity for the
        national grid.</p>
    </div>
    <div class="secondary-objective">
    <h1>🎯</h1>
        <h3>Secondary Objective</h3>
        <p> To identify, study and develop additional hydropower and renewable
        energy opportunities within Nepal by applying modern engineering
        practices, sustainable environmental standards and sound
        financial management.</p>
    </div>
</div>
</section>
<!--Company information-->
<section class="company-info">
<div class="container">
<h2>Company Information</h2>
<div class="company-info-grid">

    <div class="info-card">
    <div class="info-icon">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none"
viewBox="0 0 24 24" stroke-width="1.8"
stroke="currentColor" width="24" height="24">
<path stroke-linecap="round" stroke-linejoin="round"
d="M3 21h18M4 21V7a1 1 0 011-1h4v15M9 21V4a1 1 0 011-1h4a1 1 0 011 1v17M14 21V10h4a1 1 0 011 1v10"/>
</svg>

    </div>
    <h4>Company Name</h4>
    <p>Rasuwa Hydropower Limited</p>
    </div>

     <div class="info-card">
     <div class="info-icon">
     <svg xmlns="http://www.w3.org/2000/svg" fill="none"
viewBox="0 0 24 24" stroke-width="1.8"
stroke="currentColor" width="24" height="24">
<path stroke-linecap="round" stroke-linejoin="round"
d="M8 7V3m8 4V3m-9 8h10m-13 9h16a2 2 0 002-2V7a2 2 0 00-2-2H4a2 2 0 00-2 2v10a2 2 0 002 2z"/>
</svg>

     </div>
        <h4>Establishment</h4>
        <p>2066/02/04 B.S.</p>
      </div>

      <div class="info-card">
      <div class="info-icon">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none"
viewBox="0 0 24 24" stroke-width="1.8"
stroke="currentColor" width="24" height="24">
<path stroke-linecap="round" stroke-linejoin="round"
d="M7 21h10a2 2 0 002-2V7l-6-4H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
</svg>


      </div>
        <h4>Registration Number</h4>
        <p>62812/065/066</p>
      </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 21V7a2 2 0 012-2h14a2 2 0 012 2v14"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M7 21V10h10v11"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M7 7h.01M12 7h.01M17 7h.01"/>
            </svg>
            </div>
                <h4>Registered Office</h4>
                <p>Banasthali Chock, Kathmandu</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 11a3 3 0 100-6 3 3 0 000 6z"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 21s8-4.5 8-10a8 8 0 10-16 0c0 5.5 8 10 8 10z"/>
            </svg>
            </div>
                <h4>Project Site Office</h4>
                <p>Naukunda Rural Municipality-4, Bhorle, Rasuwa</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <rect x="2" y="4" width="20" height="16" rx="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M8 8h.01M12 8h4M8 12h8"/>
            </svg>
            </div>
                <h4>PAN Number</h4>
                <p>303630092</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M7 7h6l2 2v10a1 1 0 01-1 1H7a1 1 0 01-1-1V7z"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M7 7V5a2 2 0 012-2h6"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 13l2 2 4-4"/>
            </svg>
            </div>
                <h4>Generation License</h4>
                <p>B.B 72/073 BU 161</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 21v-1a4 4 0 014-4h8a4 4 0 014 4v1"/>
            </svg>
            </div>
                <h4>Executive Chairman</h4>
                <p>Mr. Deepak Thapa</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <circle cx="12" cy="7" r="4" stroke-linecap="round" stroke-linejoin="round"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 15c2.5-1.5 7.5-1.5 12 0"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 19c2.5-1.5 7.5-1.5 12 0"/>
            </svg>
            </div>
                <h4>Authorized Capital</h4>
                <p>NPR 40 Crore</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <circle cx="12" cy="7" r="4" stroke-linecap="round" stroke-linejoin="round"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 15c2.5-1.5 7.5-1.5 12 0"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 19c2.5-1.5 7.5-1.5 12 0"/>
            </svg>
            </div>
                <h4>Issued Capital</h4>
                <p>NPR 40 Crore</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <circle cx="12" cy="7" r="4" stroke-linecap="round" stroke-linejoin="round"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 15c2.5-1.5 7.5-1.5 12 0"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 19c2.5-1.5 7.5-1.5 12 0"/>
            </svg>
            </div>
                <h4>Paid-up Capital</h4>
                <p>NPR 24.35 Crore</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17 20v-2a4 4 0 00-4-4H11a4 4 0 00-4 4v2"/>
            <circle cx="12" cy="7" r="4" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            </div>
                <h4>Number of Shareholders</h4>
                <p>61 Shareholders</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <rect x="2" y="7" width="20" height="12" rx="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2"/>
            </svg>
            </div>
                <h4>Board of Directors</h4>
                <p>5 Members</p>
            </div>

            <div class="info-card">
            <div class="info-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2 21h20"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 3l6 6 6-6"/>
            </svg>
            </div>
                <h4>Project Status</h4>
                <p>Under Construction</p>
            </div>

    
</div>
</div>
</section>
<style>
.page-hero{
    padding: 50px 20px;
    text-align: center;
    background: linear-gradient(#fff, #f5f7fa);

}
.page-hero h1{
    font-size: 42px;
    color: var(--primary-blue);
    margin-bottom: 20px;
}
.page-hero p{
    max-width: 700px;
    margin: auto;
    color: #555;
    text-decoration: underline;
}

.company-introduction{
    padding: 10px 20px;
}
.company-introduction h2{
    color: var(--primary-blue);
}
.company-introduction p{
    margin-bottom: 15px;
    line-height: 1.7;
}
.container{
    max-width: 1100px;
    margin: auto;
    padding: 10px 0px;

}
.objectives{
    margin: 30;
    background: #f8f9fb;

}
.objective-container-grid{
    padding: 100px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 100px;
   

}
.primary-objective{
    background: rgba(255, 255, 255, 0.338);
    margin-bottom: 10px;
    text-align: center;
    border-radius: 10px;
    padding: 30px;
    box-shadow: 0 8px 20px rgba(0,0,0,1);

}
.primary-objective h3{
    color: var(--primary-blue);
}
.secondary-objective{
    background: rgba(255, 255, 255, 0.338);
    margin-bottom: 10px;
    text-align: center;
    border-radius: 10px;
    padding: 30px;
    box-shadow: 0 8px 20px rgba(0,0,0,1);
    

}
.secondary-objective h3{
    color: var(--primary-blue); 
}
.container h2{
    color: var(--primary-blue);
}
.company-info{


}
.company-info-grid{
    padding-left: 130px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap:40px;
    align-items: center;
}
.info-card{
    display: grid;
    grid-template-columns: 36px 1fr;
    gap: 12px;
    align-items: start;
    text-align: left;
    margin-bottom: 20px;
    margin-top: 10px;
}
.info-card h4{
    color: var(--primary-blue);
}
.info-card p{
    color: #555;
}
.info-icon{
    grid-column: 1;
    grid-row: 1 / span 2;
    width: 36px;
    height: 36px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--primary-blue);
    
}
.info-card h4{ margin: 0 0 4px 0; }
.info-card p{ margin: 0; }
.info-icon{
    display: flex;
    flex-direction: row;
    margin-bottom: 10px;
    color: var(--primary-blue);
}
@media(max-width:800px){
    .objective-container-grid{
        grid-template-columns: 1fr;
    }
    .company-info-grid{
        grid-template-columns: 1fr;
    }
}
</style>